=== dawoori/xml/report/Vehicle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:db="http://www.example.com/db"
        targetNamespace="http://www.example.com/db"
        elementFormDefault="qualified">

    <complexType name="VehicleType">
        <sequence>
            <element name="Body" type="string"/>
            <element name="DriveTrain">
                <complexType>
                    <sequence>
                        <element name="Engine" type="string"/>
                        <element name="Transmission" type="string"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="AutomobileType">
        <complexContent>
            <extension base="db:VehicleType">
                <sequence>
                    <element name="Trunk" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="SedanType">
        <simpleContent>
            <extension base="db:AutomobileType"/>
        </simpleContent>
    </complexType>



    <element name="Vehicle">
        <complexType>
            <choice>
                <element name="Vehicle" type="db:VehicleType"/>
                <element name="Automobile" type="db:AutomobileType"/>
            </choice>
        </complexType>
    </element>

    <element name="Vehicles">
        <complexType>
            <sequence>
                <element ref="db:Vehicle" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
</schema>

=== dawoori/xml/report/Vehicle.xml
<?xml version="1.0" encoding="UTF-8"?>
<Vehicles xmlns="http://www.example.com/db"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.example.com/db Vehicle.xsd">

    <Vehicle xsi:type="AutomobileType">
        <Body>4-door sedan</Body>
        <DriveTrain>
            <Engine>I4 2.0L CVVL/LPi</Engine>
            <Transmission>A6MF1-2</Transmission>
        </DriveTrain>
        <Trunk>Trunk Cargo</Trunk>
    </Vehicle>

    <Vehicle xsi:type="SedanType">
        <Body>4-door sedan</Body>
        <DriveTrain>
            <Engine>I4 2.0L CVVL/LPi</Engine>
            <Transmission>A6MF1-2</Transmission>
        </DriveTrain>
        <Trunk>Trunk Cargo</Trunk>
    </Vehicle>

    <Vehicle xsi:type="ConvertibleType">
        <Body>2-door convertible</Body>
        <DriveTrain>
            <Engine>5.2-liter V10 Gas</Engine>
            <Transmission>7-Speed Automatic</Transmission>
        </DriveTrain>
        <Trunk>cargo space</Trunk>
        <OperatingRoof/>
    </Vehicle>

    <Vehicle xsi:type="TruckType">
        <Body>Wing body</Body>
        <DriveTrain>
            <Engine>l4</Engine>
            <Transmission>5-Speed Automatic</Transmission>
        </DriveTrain>
        <Compartment>1 Ton</Compartment>
    </Vehicle>
</Vehicles>
